repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.289 # Ruff version.
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix, --line-length=120, --ignore=E722,--ignore=E501,--ignore=F401 ]
  - repo: https://github.com/psf/black
    rev: de65741b8d49d78fa2675ef79b799cd35e92e7c1
    hooks:
      - id: black
        language_version: python3.9
        args: [--line-length=120]
  # - repo: https://github.com/johannsdg/pre-commit-license-headers
  #   rev: v0.1.0 # Use the ref you want to point at
  #   hooks:
  #     - id: check-license-headers
  #       args:
  #         - "--template"
  #         - |
  #           Copyright IBM Corp. [YEARS] [OWNER]
  #         - "--owner=The IBM Research UK HCLS Team"