repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.289 # Ruff version.
    hooks:
      - id: ruff
        args:
          [
            --fix,
            --exit-non-zero-on-fix,
            --line-length=120,
            --ignore=E722,
            --ignore=E501,
            --ignore=F401,
          ]
  - repo: https://github.com/psf/black
    rev: de65741b8d49d78fa2675ef79b799cd35e92e7c1
    hooks:
      - id: black
        language_version: python3.9
        args: [--line-length=120]
