version: 1
formatters:
  simple:
    format: '%(name)s - %(asctime)s - %(filename)s - %(funcName)s() - %(levelname)s : %(message)s'
handlers:
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename:
    mode: 'a'
loggers:
  OmicLogger:
    level: DEBUG
    handlers: [file]
    propagate: no